version: '3.8'
services:
  webserver:
    build: docker/general
    container_name: ubuntu.${APP_NAMESPACE}
    depends_on:
      - mariadb
    volumes:
      - .:/var/www/html
    ports:
      - '${NGINX_HTTP_PORT:-8000}:80'
      - '${NGINX_HTTP_PORT:-8001}:443'
    networks:
      - web
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-http.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.web-https.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.web-https.tls=true
  mariadb:
    image: 'mariadb:10'
    container_name: mariadb.${APP_NAMESPACE}
    ports:
      - '${FORWARD_DB_PORT:-}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-laravel}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
      MYSQL_USER: '${DB_USERNAME:-laravel}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './docker/mariadb/data:/var/lib/mysql'
    networks:
      - web
      - default
    labels:
      - traefik.enable=false
  redis:
    image: redis
    container_name: redis.${APP_NAMESPACE}
    volumes:
      - ./docker/redis/data:/data
    ports:
      - '${REDIS_PORT:-6379}:${REDIS_PORT:-6379}'
    networks:
      - default
    labels:
      - traefik.enable=false

networks:
  web:
    name: traefik_default
    external: true
